function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 05-Feb-2023 19:44:43

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot1 = plot(X1,Y1);

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,0.002,4.24542753899333e-06);
% Create datatip
datatip(plot1,'DataIndex',3);

% Create ylabel
ylabel('Normal acceleration (g)');

% Create xlabel
xlabel('Time (s)');

hold(axes1,'off');
